version: "3.9"

services:
    app:
        build: .
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        environment:
            - NODE_ENV=production
            - DATA_PATH=/app/data
            - SERVER_PORT=${SERVER_PORT}
        volumes:
            - "${DATA_PATH}:/app/data"
