version: "3.9"

services:
  app:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - CLOUDS_PATH=${CLOUDS_PATH}
      - OUTPUT_PATH=${OUTPUT_PATH}
      - SERVER_PORT=${SERVER_PORT}
    volumes:
      - "${DATA_PATH}:/app/data"
