export const defaultHotkeys = {
    camera: {
        changeTarget: "---",
        switchToOriginView: "h",
        switchToFrontView: "---",
        switchToLeftView: "---",
        switchToTopView: "---",
        switchToRightView: "---",
        switchToBackView: "---",
    },
    playback: {
        goToFirstFrame: "---",
        goToPreviousFrame: ",",
        play: "p",
        goToNextFrame: ".",
        goToLastFrame: "---",
        playCycle: "---",
        playSpeed: "---",
    },
    tools: {
        handPointer: "q",
        brushTool: "x",
        polygonTool: "c",
        lassoTool: "v",
        rectangleTool: "---",
        propagateLastPolygon: "z",
    },
    modes: {
        paintFill: "---",
        paintDepth: "---",
        filterHide: ";",
        filterCrop: "'",
        filterReveal: "---",
    },
    cuboids: {
        applyTransform: "---",
        fixOdometryFrame: "---",
        copyObjectTransform: "---",
        transformNull: "r",
        transformTranslate: "t",
        transformRotate: "y",
        transformScale: "u",
        openBatchMode: "tab",
        rotateObjectPlus: "---",
        rotateObjectMinus: "---",
        flipObjectZ: "f",
        switchViewToCuboid: "g",
    },
    misc: {
        undoAction: "ctrl+z",
        redoAction: "ctrl+x",
        toggleGlobalBox: "[",
        toggleCircleRuler: "]",
        hideShowAll: "b",
        showFilteredPoints: "n",
    },
    fixed: {
        unselectObject: "esc",
    },
};
