export const defaultHotkeys = {
    camera: {
        changeTarget: "---",
        switchToOriginView: "---",
        switchToFrontView: "---",
        switchToLeftView: "---",
        switchToTopView: "---",
        switchToRightView: "---",
        switchToBackView: "---",
    },
    playback: {
        goToFirstFrame: "---",
        goToPreviousFrame: "---",
        play: "---",
        goToNextFrame: "---",
        goToLastFrame: "---",
        playCycle: "---",
        playSpeed: "---",
    },
    tools: {
        handPointer: "---",
        brushTool: "---",
        polygonTool: "---",
        lassoTool: "---",
        rectangleTool: "---",
    },
    modes: {
        paintFill: "---",
        paintDepth: "---",
        filterHide: "---",
        filterCrop: "---",
        filterReveal: "---",
    },
    cuboids: {
        applyTransform: "---",
        fixOdometryFrame: "---",
        copyObjectTransform: "---",
        transformNull: "---",
        transformTranslate: "---",
        transformRotate: "---",
        transformScale: "---",
        openBatchMode: "tab",
        rotateObjectPlus: "---",
        rotateObjectMinus: "---",
        flipObjectZ: "---",
        switchViewToCuboid: "---",
    },
    misc: {
        undoAction: "---",
        redoAction: "---",
        toggleGlobalBox: "---",
        toggleCircleRuler: "---",
        hideShowAll: "---",
        showFilteredPoints: "---",
    },
    fixed: {
        unselectObject: "esc",
    },
};
